services:
  app:
    image: patientor-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/ap
    ports:
      - 3000:3000
    container_name: patientor-frontend-dev
  server:
    image: patientor-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    container_name: patientor-backend-dev