version: '3.8'

services:
  backend:
    image: todo-backend
    build: . 
    ports:                
      - 3000:3000
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
      - redis_data:/data/db

volumes:
  mongo_data:
  redis_data: